### ISSUE TITLE
Add LibreSSL suite

### ISSUE THREAD

**Issue by lanodan** [aeris/cryptcheck-rails#6]
LibreSSL have differents ciphers (GOST, CHACHA20, Poly1305, …) compared to OpenSSL and have removed SSLv3.

**Comment by aeris** [comment]
Because LibreSSL drops support of protocols (SSLv2, SSLv3) and ciphers (anonymous, export…), I can’t use it for cryptcheck.
Better way will be to manage a custom TLS handshake to be able to support whatever we want. But require a lot of work…
